apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "graphql-server.fullname" . }}
  labels:
    app: {{ template "graphql-server.fullname" . }}
    chart: {{ template "graphql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "graphql-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "graphql-server.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "--log-level",
            "{{ .Values.logLevel }}",
            "start-server",
          ]
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
      {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}