run:
  skip-dirs:
    - internal/graphql/generated
    - internal/graphql/genresolver
  skip-files:
    - ".*_test\\.go$"
  timeout: 5m
  allow-parallel-runners: true
linters-settings:
    revive:
      rules:
        - name: var-naming
          arguments: [["ID"]]
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
