issues:
  exclude-dirs:
    - internal/graphql/generated
    - internal/graphql/genresolver
run:
  tests: false
  timeout: 5m
  allow-parallel-runners: true
  # golangci-lint config
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  revive:
     rules:
       - name: var-naming
         arguments: [["ID"]]
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
