// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clients

import (
	"context"

	"github.com/dictyBase/go-genproto/dictybaseapis/feature_annotation"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockFeatureAnnotationServiceClient creates a new instance of MockFeatureAnnotationServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureAnnotationServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureAnnotationServiceClient {
	mock := &MockFeatureAnnotationServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureAnnotationServiceClient is an autogenerated mock type for the FeatureAnnotationServiceClient type
type MockFeatureAnnotationServiceClient struct {
	mock.Mock
}

type MockFeatureAnnotationServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureAnnotationServiceClient) EXPECT() *MockFeatureAnnotationServiceClient_Expecter {
	return &MockFeatureAnnotationServiceClient_Expecter{mock: &_m.Mock}
}

// AddTag provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) AddTag(ctx context.Context, in *feature_annotation.AddTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddTag")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.AddTagRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.AddTagRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.AddTagRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_AddTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTag'
type MockFeatureAnnotationServiceClient_AddTag_Call struct {
	*mock.Call
}

// AddTag is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) AddTag(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_AddTag_Call {
	return &MockFeatureAnnotationServiceClient_AddTag_Call{Call: _e.mock.On("AddTag",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_AddTag_Call) Run(run func(ctx context.Context, in *feature_annotation.AddTagRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_AddTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.AddTagRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_AddTag_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_AddTag_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_AddTag_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.AddTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_AddTag_Call {
	_c.Call.Return(run)
	return _c
}

// AddTags provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) AddTags(ctx context.Context, in *feature_annotation.AddTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddTags")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.AddTagsRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.AddTagsRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.AddTagsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_AddTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTags'
type MockFeatureAnnotationServiceClient_AddTags_Call struct {
	*mock.Call
}

// AddTags is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) AddTags(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_AddTags_Call {
	return &MockFeatureAnnotationServiceClient_AddTags_Call{Call: _e.mock.On("AddTags",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_AddTags_Call) Run(run func(ctx context.Context, in *feature_annotation.AddTagsRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_AddTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.AddTagsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_AddTags_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_AddTags_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_AddTags_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.AddTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_AddTags_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFeatureAnnotation provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) CreateFeatureAnnotation(ctx context.Context, in *feature_annotation.NewFeatureAnnotation, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateFeatureAnnotation")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.NewFeatureAnnotation, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.NewFeatureAnnotation, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.NewFeatureAnnotation, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFeatureAnnotation'
type MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call struct {
	*mock.Call
}

// CreateFeatureAnnotation is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) CreateFeatureAnnotation(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call {
	return &MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call{Call: _e.mock.On("CreateFeatureAnnotation",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call) Run(run func(ctx context.Context, in *feature_annotation.NewFeatureAnnotation, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.NewFeatureAnnotation), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.NewFeatureAnnotation, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_CreateFeatureAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFeatureAnnotation provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) DeleteFeatureAnnotation(ctx context.Context, in *feature_annotation.DeleteFeatureAnnotationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteFeatureAnnotation")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.DeleteFeatureAnnotationRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.DeleteFeatureAnnotationRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.DeleteFeatureAnnotationRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFeatureAnnotation'
type MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call struct {
	*mock.Call
}

// DeleteFeatureAnnotation is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) DeleteFeatureAnnotation(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call {
	return &MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call{Call: _e.mock.On("DeleteFeatureAnnotation",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call) Run(run func(ctx context.Context, in *feature_annotation.DeleteFeatureAnnotationRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.DeleteFeatureAnnotationRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call) Return(empty *emptypb.Empty, err error) *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.DeleteFeatureAnnotationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)) *MockFeatureAnnotationServiceClient_DeleteFeatureAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatureAnnotation provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) GetFeatureAnnotation(ctx context.Context, in *feature_annotation.FeatureAnnotationId, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFeatureAnnotation")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureAnnotationId, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureAnnotationId, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.FeatureAnnotationId, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatureAnnotation'
type MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call struct {
	*mock.Call
}

// GetFeatureAnnotation is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) GetFeatureAnnotation(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call {
	return &MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call{Call: _e.mock.On("GetFeatureAnnotation",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call) Run(run func(ctx context.Context, in *feature_annotation.FeatureAnnotationId, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.FeatureAnnotationId), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.FeatureAnnotationId, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_GetFeatureAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatureAnnotationByName provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) GetFeatureAnnotationByName(ctx context.Context, in *feature_annotation.FeatureName, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFeatureAnnotationByName")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureName, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureName, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.FeatureName, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatureAnnotationByName'
type MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call struct {
	*mock.Call
}

// GetFeatureAnnotationByName is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) GetFeatureAnnotationByName(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call {
	return &MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call{Call: _e.mock.On("GetFeatureAnnotationByName",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call) Run(run func(ctx context.Context, in *feature_annotation.FeatureName, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.FeatureName), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.FeatureName, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_GetFeatureAnnotationByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListFeatureAnnotationsByDOI provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) ListFeatureAnnotationsByDOI(ctx context.Context, in *feature_annotation.DOI, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListFeatureAnnotationsByDOI")
	}

	var r0 *feature_annotation.FeatureAnnotationCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.DOI, ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.DOI, ...grpc.CallOption) *feature_annotation.FeatureAnnotationCollection); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotationCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.DOI, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFeatureAnnotationsByDOI'
type MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call struct {
	*mock.Call
}

// ListFeatureAnnotationsByDOI is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) ListFeatureAnnotationsByDOI(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call {
	return &MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call{Call: _e.mock.On("ListFeatureAnnotationsByDOI",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call) Run(run func(ctx context.Context, in *feature_annotation.DOI, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.DOI), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call) Return(featureAnnotationCollection *feature_annotation.FeatureAnnotationCollection, err error) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call {
	_c.Call.Return(featureAnnotationCollection, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.DOI, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error)) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByDOI_Call {
	_c.Call.Return(run)
	return _c
}

// ListFeatureAnnotationsByPubmedId provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) ListFeatureAnnotationsByPubmedId(ctx context.Context, in *feature_annotation.PubmedId, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListFeatureAnnotationsByPubmedId")
	}

	var r0 *feature_annotation.FeatureAnnotationCollection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.PubmedId, ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.PubmedId, ...grpc.CallOption) *feature_annotation.FeatureAnnotationCollection); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotationCollection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.PubmedId, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFeatureAnnotationsByPubmedId'
type MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call struct {
	*mock.Call
}

// ListFeatureAnnotationsByPubmedId is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) ListFeatureAnnotationsByPubmedId(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call {
	return &MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call{Call: _e.mock.On("ListFeatureAnnotationsByPubmedId",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call) Run(run func(ctx context.Context, in *feature_annotation.PubmedId, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.PubmedId), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call) Return(featureAnnotationCollection *feature_annotation.FeatureAnnotationCollection, err error) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call {
	_c.Call.Return(featureAnnotationCollection, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.PubmedId, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotationCollection, error)) *MockFeatureAnnotationServiceClient_ListFeatureAnnotationsByPubmedId_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTag provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) RemoveTag(ctx context.Context, in *feature_annotation.RemoveTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveTag")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.RemoveTagRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.RemoveTagRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.RemoveTagRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_RemoveTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTag'
type MockFeatureAnnotationServiceClient_RemoveTag_Call struct {
	*mock.Call
}

// RemoveTag is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) RemoveTag(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_RemoveTag_Call {
	return &MockFeatureAnnotationServiceClient_RemoveTag_Call{Call: _e.mock.On("RemoveTag",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTag_Call) Run(run func(ctx context.Context, in *feature_annotation.RemoveTagRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_RemoveTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.RemoveTagRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTag_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_RemoveTag_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTag_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.RemoveTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_RemoveTag_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTags provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) RemoveTags(ctx context.Context, in *feature_annotation.RemoveTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveTags")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.RemoveTagsRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.RemoveTagsRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.RemoveTagsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_RemoveTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTags'
type MockFeatureAnnotationServiceClient_RemoveTags_Call struct {
	*mock.Call
}

// RemoveTags is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) RemoveTags(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_RemoveTags_Call {
	return &MockFeatureAnnotationServiceClient_RemoveTags_Call{Call: _e.mock.On("RemoveTags",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTags_Call) Run(run func(ctx context.Context, in *feature_annotation.RemoveTagsRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_RemoveTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.RemoveTagsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTags_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_RemoveTags_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_RemoveTags_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.RemoveTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_RemoveTags_Call {
	_c.Call.Return(run)
	return _c
}

// SetTags provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) SetTags(ctx context.Context, in *feature_annotation.SetTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetTags")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.SetTagsRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.SetTagsRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.SetTagsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_SetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTags'
type MockFeatureAnnotationServiceClient_SetTags_Call struct {
	*mock.Call
}

// SetTags is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) SetTags(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_SetTags_Call {
	return &MockFeatureAnnotationServiceClient_SetTags_Call{Call: _e.mock.On("SetTags",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_SetTags_Call) Run(run func(ctx context.Context, in *feature_annotation.SetTagsRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_SetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.SetTagsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_SetTags_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_SetTags_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_SetTags_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.SetTagsRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_SetTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFeatureAnnotation provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) UpdateFeatureAnnotation(ctx context.Context, in *feature_annotation.FeatureAnnotationUpdate, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeatureAnnotation")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureAnnotationUpdate, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.FeatureAnnotationUpdate, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.FeatureAnnotationUpdate, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFeatureAnnotation'
type MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call struct {
	*mock.Call
}

// UpdateFeatureAnnotation is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) UpdateFeatureAnnotation(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call {
	return &MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call{Call: _e.mock.On("UpdateFeatureAnnotation",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call) Run(run func(ctx context.Context, in *feature_annotation.FeatureAnnotationUpdate, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.FeatureAnnotationUpdate), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.FeatureAnnotationUpdate, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_UpdateFeatureAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTag provides a mock function for the type MockFeatureAnnotationServiceClient
func (_mock *MockFeatureAnnotationServiceClient) UpdateTag(ctx context.Context, in *feature_annotation.UpdateTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 *feature_annotation.FeatureAnnotation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.UpdateTagRequest, ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *feature_annotation.UpdateTagRequest, ...grpc.CallOption) *feature_annotation.FeatureAnnotation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature_annotation.FeatureAnnotation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *feature_annotation.UpdateTagRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureAnnotationServiceClient_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type MockFeatureAnnotationServiceClient_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *MockFeatureAnnotationServiceClient_Expecter) UpdateTag(ctx interface{}, in interface{}, opts ...interface{}) *MockFeatureAnnotationServiceClient_UpdateTag_Call {
	return &MockFeatureAnnotationServiceClient_UpdateTag_Call{Call: _e.mock.On("UpdateTag",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFeatureAnnotationServiceClient_UpdateTag_Call) Run(run func(ctx context.Context, in *feature_annotation.UpdateTagRequest, opts ...grpc.CallOption)) *MockFeatureAnnotationServiceClient_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*feature_annotation.UpdateTagRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_UpdateTag_Call) Return(featureAnnotation *feature_annotation.FeatureAnnotation, err error) *MockFeatureAnnotationServiceClient_UpdateTag_Call {
	_c.Call.Return(featureAnnotation, err)
	return _c
}

func (_c *MockFeatureAnnotationServiceClient_UpdateTag_Call) RunAndReturn(run func(ctx context.Context, in *feature_annotation.UpdateTagRequest, opts ...grpc.CallOption) (*feature_annotation.FeatureAnnotation, error)) *MockFeatureAnnotationServiceClient_UpdateTag_Call {
	_c.Call.Return(run)
	return _c
}
