name: Build
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      redis:
        image: redis:5.0.9-alpine
        ports:
          - 6379/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13.9
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          REDIS_MASTER_SERVICE_HOST: localhost
          REDIS_MASTER_SERVICE_PORT: ${{ job.services.redis.ports[6379] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.9
      - name: check out code
        uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t dictybase/graphql-server:develop-$(git rev-parse --short HEAD) -f build/package/Dockerfile .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push dictybase/graphql-server:develop-$(git rev-parse --short HEAD)
