package genresolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/dictyBase/go-genproto/dictybaseapis/content"
	"github.com/dictyBase/go-genproto/dictybaseapis/order"
	"github.com/dictyBase/go-genproto/dictybaseapis/user"
	"github.com/dictyBase/graphql-server/internal/graphql/generated"
	"github.com/dictyBase/graphql-server/internal/graphql/models"
)

// GeneOntologyAnnotation is the resolver for the geneOntologyAnnotation field.
func (r *queryResolver) GeneOntologyAnnotation(ctx context.Context, gene string) ([]*models.GOAnnotation, error) {
	panic(fmt.Errorf("not implemented: GeneOntologyAnnotation - geneOntologyAnnotation"))
}

// GeneGeneralInformation is the resolver for the geneGeneralInformation field.
func (r *queryResolver) GeneGeneralInformation(ctx context.Context, gene string) (*models.GeneGeneralInfo, error) {
	panic(fmt.Errorf("not implemented: GeneGeneralInformation - geneGeneralInformation"))
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, id string) (*content.Content, error) {
	panic("not implemented")
}

// ContentBySlug is the resolver for the contentBySlug field.
func (r *queryResolver) ContentBySlug(ctx context.Context, slug string) (*content.Content, error) {
	panic("not implemented")
}

// ListContentByNamespace is the resolver for the listContentByNamespace field.
func (r *queryResolver) ListContentByNamespace(ctx context.Context, namespace string) ([]*content.Content, error) {
	panic(fmt.Errorf("not implemented: ListContentByNamespace - listContentByNamespace"))
}

// Organism is the resolver for the organism field.
func (r *queryResolver) Organism(ctx context.Context, taxonID string) (*models.Organism, error) {
	panic("not implemented")
}

// ListOrganisms is the resolver for the listOrganisms field.
func (r *queryResolver) ListOrganisms(ctx context.Context) ([]*models.Organism, error) {
	panic("not implemented")
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*order.Order, error) {
	panic("not implemented")
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context, cursor *int, limit *int, filter *string) (*models.OrderListWithCursor, error) {
	panic("not implemented")
}

// Publication is the resolver for the publication field.
func (r *queryResolver) Publication(ctx context.Context, id string) (*models.Publication, error) {
	panic("not implemented")
}

// ListRecentPublications is the resolver for the listRecentPublications field.
func (r *queryResolver) ListRecentPublications(ctx context.Context, limit int) ([]*models.Publication, error) {
	panic(fmt.Errorf("not implemented: ListRecentPublications - listRecentPublications"))
}

// ListPublicationsWithGene is the resolver for the listPublicationsWithGene field.
func (r *queryResolver) ListPublicationsWithGene(ctx context.Context, gene string) ([]*models.PublicationWithGene, error) {
	panic(fmt.Errorf("not implemented: ListPublicationsWithGene - listPublicationsWithGene"))
}

// Plasmid is the resolver for the plasmid field.
func (r *queryResolver) Plasmid(ctx context.Context, id string) (*models.Plasmid, error) {
	panic("not implemented")
}

// Strain is the resolver for the strain field.
func (r *queryResolver) Strain(ctx context.Context, id string) (*models.Strain, error) {
	panic("not implemented")
}

// ListStrainsWithGene is the resolver for the listStrainsWithGene field.
func (r *queryResolver) ListStrainsWithGene(ctx context.Context, gene string) ([]*models.Strain, error) {
	panic(fmt.Errorf("not implemented: ListStrainsWithGene - listStrainsWithGene"))
}

// ListStrains is the resolver for the listStrains field.
func (r *queryResolver) ListStrains(ctx context.Context, cursor *int, limit *int, filter *models.StrainListFilter) (*models.StrainListWithCursor, error) {
	panic("not implemented")
}

// ListPlasmids is the resolver for the listPlasmids field.
func (r *queryResolver) ListPlasmids(ctx context.Context, cursor *int, limit *int, filter *models.PlasmidListFilter) (*models.PlasmidListWithCursor, error) {
	panic("not implemented")
}

// ListStrainsWithAnnotation is the resolver for the listStrainsWithAnnotation field.
func (r *queryResolver) ListStrainsWithAnnotation(ctx context.Context, cursor *int, limit *int, typeArg string, annotation string) (*models.StrainListWithCursor, error) {
	panic("not implemented")
}

// ListPlasmidsWithAnnotation is the resolver for the listPlasmidsWithAnnotation field.
func (r *queryResolver) ListPlasmidsWithAnnotation(ctx context.Context, cursor *int, limit *int, typeArg string, annotation string) (*models.PlasmidListWithCursor, error) {
	panic("not implemented")
}

// ListRecentPlasmids is the resolver for the listRecentPlasmids field.
func (r *queryResolver) ListRecentPlasmids(ctx context.Context, limit int) ([]*models.Plasmid, error) {
	panic(fmt.Errorf("not implemented: ListRecentPlasmids - listRecentPlasmids"))
}

// ListRecentStrains is the resolver for the listRecentStrains field.
func (r *queryResolver) ListRecentStrains(ctx context.Context, limit int) ([]*models.Strain, error) {
	panic(fmt.Errorf("not implemented: ListRecentStrains - listRecentStrains"))
}

// ListPhenotypes is the resolver for the listPhenotypes field.
func (r *queryResolver) ListPhenotypes(ctx context.Context, search string) ([]string, error) {
	panic(fmt.Errorf("not implemented: ListPhenotypes - listPhenotypes"))
}

// ListPhenotypeEnvironments is the resolver for the listPhenotypeEnvironments field.
func (r *queryResolver) ListPhenotypeEnvironments(ctx context.Context, search string) ([]string, error) {
	panic(fmt.Errorf("not implemented: ListPhenotypeEnvironments - listPhenotypeEnvironments"))
}

// ListPhenotypeAssays is the resolver for the listPhenotypeAssays field.
func (r *queryResolver) ListPhenotypeAssays(ctx context.Context, search string) ([]string, error) {
	panic(fmt.Errorf("not implemented: ListPhenotypeAssays - listPhenotypeAssays"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*user.User, error) {
	panic("not implemented")
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*user.User, error) {
	panic("not implemented")
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, pagenum string, pagesize string, filter string) (*models.UserList, error) {
	panic("not implemented")
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*user.Role, error) {
	panic("not implemented")
}

// ListRoles is the resolver for the listRoles field.
func (r *queryResolver) ListRoles(ctx context.Context) ([]*user.Role, error) {
	panic("not implemented")
}

// Permission is the resolver for the permission field.
func (r *queryResolver) Permission(ctx context.Context, id string) (*user.Permission, error) {
	panic("not implemented")
}

// ListPermissions is the resolver for the listPermissions field.
func (r *queryResolver) ListPermissions(ctx context.Context) ([]*user.Permission, error) {
	panic("not implemented")
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
