type UserInfo {
  first_name: String
  last_name: String
  organization: String
  first_address: String
  second_address: String
  city: String
  state: String
  zipcode: String
  country: String
  phone: String
}

type Order {
  id: ID!
  created_at: Timestamp!
  updated_at: Timestamp!
  courier: String
  courier_account: String
  comments: String
  payment: String
  purchase_order_num: String
  status: StatusEnum
  consumer: User
  payer: User
  purchaser: User
  items: [Stock!]
  consumer_info: UserInfo
  payer_info: UserInfo
}

type OrderListWithCursor {
  orders: [Order!]!
  nextCursor: Int!
  previousCursor: Int!
  limit: Int
  totalCount: Int!
}

enum StatusEnum {
  IN_PREPARATION
  GROWING
  CANCELLED
  SHIPPED
}

input CreateOrderInput {
  courier: String!
  courier_account: String!
  comments: String
  payment: String!
  purchase_order_num: String
  status: StatusEnum!
  consumer: String!
  payer: String!
  purchaser: String!
  items: [String!]!
  consumer_info: UserInfoInput
  payer_info: UserInfoInput
}

input UserInfoInput {
  first_name: String
  last_name: String
  organization: String
  first_address: String
  second_address: String
  city: String
  state: String
  zipcode: String
  country: String
  phone: String
}

input UpdateOrderInput {
  courier: String
  courier_account: String
  comments: String
  payment: String
  purchase_order_num: String
  status: StatusEnum
  items: [String!]
}
